services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=SenhaForte123
    ports:
      - "1433:1433"
    volumes:
      - mssql_root:/var/opt/mssql
      - ../backups:/var/opt/mssql/backups
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -C -Q 'SELECT 1' || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
      - ../.streamlit:/app/.streamlit:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  mssql_root:
