[mssql]
server = "localhost,1433"     # ou localhost,11433 se mapeou 11433:1433
database = "salesDB"
username = "sa"
password = "SenhaForte123"    # a MESMA do compose
driver = "ODBC Driver 18 for SQL Server"
trust_server_certificate = "yes"
